### ISSUE TITLE
More Courses

### ISSUE THREAD

**Issue by RamtinMoslemi** [amirabbasasadi/mathematics-computerscience-courses#1]
Thanks for the awesome list!
Here are some other courses that might be interesting:

- [Stanford CS224W: Machine Learning with Graphs](https://youtube.com/playlist?list=PLoROMvodv4rPLKxIpqhjhPgdQy7imNkDn)
- [Geometric Deep Learning](https://youtube.com/playlist?list=PLn2-dEmQeTfSLXW8yXP4q_Ii58wFdxb3C&si=ZDSVx4FhZgL95lmd)
- [Stanford CS236: Deep Generative Models](https://youtube.com/playlist?list=PLoROMvodv4rPOWA-omMM6STXaWW4FvJT8)
- [UC Berkeley CS294: Deep Unsupervised Learning](https://www.youtube.com/playlist?list=PLwRJQ4m4UJjPIvv4kgBkvu_uygrV3ut_U)
- [Stanford CS364B: Advanced Mechanism Design](https://youtube.com/playlist?list=PLEGCF-WLh2RI77PL4gwLld_OU9Zh3TCX9&si=rwpR2Rzt6RZ9CJbl) (takes place at the end of [Algorithmic Game Theory](https://github.com/amirabbasasadi/mathematics-computerscience-courses?tab=readme-ov-file#algorithmic-game-theory) by Tim Roughgarden)
- [High-Dimensional Probability](https://www.youtube.com/playlist?list=PLPjEEUWIWhQV7X6dXfrVP3w0KBBLBVJ0j) (which accompanies [the book](https://www.math.uci.edu/~rvershyn/papers/HDP-book/HDP-book.html))
- [Deep Learning for Computer Vision](https://www.youtube.com/playlist?list=PL5-TkQAfAZFbzxjBHtzdVCWE0Zbhomg7r)

**Comment by amirabbasasadi** [comment]
Thanks Ramtin, Great courses . feel free to make a pull request or I will add them later.
